version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: V3test
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Taipei
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: V3test
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 3
