version: 2
multi-ecosystem-groups:
  routine-v3test:
    target-branch: V3test
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Taipei

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: routine-v3test
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: routine-v3test
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
