import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const srcDir = path.join(root, "src");
const outFile = path.join(root, "docs", "ai-map.generated.md");

const groupMatchers = [
  { name: "dashboard", test: (p) => p.includes("components/dashboard") || p.includes("utils/historyStats") },
  { name: "session", test: (p) => p.includes("/session/") },
  { name: "template", test: (p) => p.includes("/template/") },
  { name: "history", test: (p) => p.includes("/history/") || p.includes("useHistory") },
  { name: "ai-generator", test: (p) => p.includes("features/ai-generator") },
  { name: "i18n", test: (p) => p.startsWith("i18n/") },
];

function walkFiles(dir, relBase = "") {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const rel = path.join(relBase, entry.name);
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(abs, rel));
    } else {
      files.push(rel.replace(/\\/g, "/"));
    }
  }
  return files;
}

function pickTop(files, limit = 12) {
  return files
    .filter((p) => /\.(ts|tsx)$/.test(p))
    .sort((a, b) => a.localeCompare(b))
    .slice(0, limit);
}

const allFiles = walkFiles(srcDir);
const groups = new Map();

for (const matcher of groupMatchers) {
  groups.set(matcher.name, pickTop(allFiles.filter((p) => matcher.test(p))));
}

const ungrouped = allFiles.filter((p) => !groupMatchers.some((g) => g.test(p)));

const lines = [];
lines.push("# AI Map (Generated)");
lines.push("");
lines.push("This file is auto-generated by `npm run docs:ai-map`.");
lines.push("Do not hand-edit this file. Edit `docs/ai-map.md` for manual guidance.");
lines.push("");

for (const [name, files] of groups.entries()) {
  lines.push(`## ${name}`);
  if (files.length === 0) {
    lines.push("- (no files matched)");
  } else {
    for (const f of files) {
      lines.push(`- \`src/${f}\``);
    }
  }
  lines.push("");
}

lines.push("## other-src-samples");
for (const f of pickTop(ungrouped, 20)) {
  lines.push(`- \`src/${f}\``);
}
lines.push("");

fs.writeFileSync(outFile, `${lines.join("\n")}\n`, "utf8");
console.log(`Generated ${path.relative(root, outFile)}`);

